# Generated by Django 3.1.5 on 2021-02-02 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210202_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 12, 9, 28, 509688, tzinfo=utc)),
        ),
    ]
