# Generated by Django 3.1.5 on 2021-02-02 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210202_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 12, 18, 0, 151982, tzinfo=utc)),
        ),
    ]
