# Generated by Django 3.1.5 on 2021-02-02 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210202_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 15, 51, 52, 481477, tzinfo=utc)),
        ),
    ]
